In [1]:
#DataFrame when you combine multiple series together
import numpy as np
import pandas as pd

In [2]:
#create data frame using dictionary
data={
    'Name':['john', 'anna','peter','linda'],
    'Age':[28,34,29,42],
    'city':['new york','paris','berlin','london'],
    'Salary':[65000,70000,80000,62000]
}
df=pd.DataFrame(data)

In [3]:
df

    Name  Age      city  Salary
0   john   28  new york   65000
1   anna   34     paris   70000
2  peter   29    berlin   80000
3  linda   42    london   62000

In [4]:
#create data frame using list 
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
col = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns =col)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [5]:
#selection and indexing of columns 
df2["Name"]

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [6]:
#column selection
df2[["City","Name"]]

       City   Name
0  New York   John
1     Paris   Anna
2    Berlin  Peter
3    London  Linda

In [7]:
#creating new column
df2["Designation"]=["Doctor","engineer","HR","lawyer"]
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    engineer
2  Peter   29    Berlin   62000          HR
3  Linda   42    London   85000      lawyer

In [8]:
#Removing column from data
df2.drop('Designation',axis = 1,inplace=True)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [11]:
#Removing row from data
df2.drop(0,axis = 0)

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [12]:
#selecting Row

In [13]:
df2.loc[0]  #0th row

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [15]:
df2.loc[[1,2]]  #multiple rows

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000

In [16]:
#selecting subset of  rows and columns

In [18]:
df2.loc[[0,1]][['City','Salary']]

       City  Salary
0  New York   65000
1     Paris   70000

In [19]:
df2.loc[[2,3]][['Name','Age']]

    Name  Age
2  Peter   29
3  Linda   42

In [20]:
#conditional selection

In [21]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [29]:
#only want data of those people whose age is above 30
df2[df2["Age"]>30 ]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [34]:
#only want data of those people whose age is above 30 and city=paris
df2[(df2["Age"]>30) & (df2["City"] == 'Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000