In [1]:
import numpy as np
import pandas as pd

Finding Missing Data

In [3]:
data = {
    'A':[1,2,np.nan,4,5],
    'B':[np.nan,2,3,4,5],
    'C':[1,2,3,np.nan,np.nan],
    'D':[1,np.nan,np.nan,np.nan,5]
}
df=pd.DataFrame(data)
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [6]:
#isna helps to find null values
df.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [7]:
#count the total null values 
df.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [9]:
#chcek if is their any null value in each column
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

Removing Null values

In [13]:
#whole dataset is get delete
df.dropna()

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [14]:
#threshold
df.dropna(thresh=3)  #remove the row only if it contains less than 3 non null values

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
4  5.0  5.0  NaN  5.0

Filling Missing Data

In [15]:
#fill all the missing values with 0
df.fillna(0)

     A    B    C    D
0  1.0  0.0  1.0  1.0
1  2.0  2.0  2.0  0.0
2  0.0  3.0  3.0  0.0
3  4.0  4.0  0.0  0.0
4  5.0  5.0  0.0  5.0

In [17]:
#fill missing values with diff values for each column
values= {'A':0,'B':7,'C':2,'D':4}
df.fillna(value=values)

     A    B    C    D
0  1.0  7.0  1.0  1.0
1  2.0  2.0  2.0  4.0
2  0.0  3.0  3.0  4.0
3  4.0  4.0  2.0  4.0
4  5.0  5.0  2.0  5.0

In [18]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [ ]:
#at the place of nan now we want mean
df.fillna